
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 12 11:45:39 BRT 2017
//----------------------------------------------------

package compilador;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 8;
  public static final int IDENT = 21;
  public static final int ELSE = 4;
  public static final int PLUS = 6;
  public static final int INT = 20;
  public static final int RPAREN = 19;
  public static final int THEN = 3;
  public static final int SEMI = 14;
  public static final int COM = 15;
  public static final int IF = 2;
  public static final int LPAREN = 18;
  public static final int LE = 12;
  public static final int GR = 13;
  public static final int ASM = 10;
  public static final int EOF = 0;
  public static final int DEF = 5;
  public static final int DIV = 9;
  public static final int MINUS = 7;
  public static final int error = 1;
  public static final int DOT = 16;
  public static final int EQ = 11;
  public static final int DDOT = 17;
}

