/*
 * Generated by classgen, version 1.5
 * 7/12/17 11:45 AM
 */
package ast;

public class Decla extends E {

  public String id;
  public Seq seq;

  public Decla (String id, Seq seq) {
    this.id = id;
    this.seq = seq;
    if (seq != null) seq.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (seq != null) seq.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (seq != null) seq.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (seq != null) seq.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Decla(\n");
    buffer.append("  "+tab+id);
    buffer.append("\n");
      if (seq != null)
        buffer.append(seq.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Decla]");
    return buffer.toString();
  }
}
