/*
 * Generated by classgen, version 1.5
 * 7/12/17 11:45 AM
 */
package ast;

public class Ident extends E {

  public String nome;

  public Ident (String nome) {
    this.nome = nome;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("Ident(\n");
    buffer.append("  "+tab+nome);
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [Ident]");
    return buffer.toString();
  }
}
