/*
 * Generated by classgen, version 1.5
 * 7/12/17 11:45 AM
 */
package ast;

public class IfThenElse extends E {

  public E e1;
  public String oprel;
  public E e2;
  public E thenStr;
  public E elseStr;

  public IfThenElse (E e1, String oprel, E e2, E thenStr, E elseStr) {
    this.e1 = e1;
    if (e1 != null) e1.setParent(this);
    this.oprel = oprel;
    this.e2 = e2;
    if (e2 != null) e2.setParent(this);
    this.thenStr = thenStr;
    if (thenStr != null) thenStr.setParent(this);
    this.elseStr = elseStr;
    if (elseStr != null) elseStr.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (e1 != null) e1.accept(visitor);
    if (e2 != null) e2.accept(visitor);
    if (thenStr != null) thenStr.accept(visitor);
    if (elseStr != null) elseStr.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (e1 != null) e1.traverseTopDown(visitor);
    if (e2 != null) e2.traverseTopDown(visitor);
    if (thenStr != null) thenStr.traverseTopDown(visitor);
    if (elseStr != null) elseStr.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (e1 != null) e1.traverseBottomUp(visitor);
    if (e2 != null) e2.traverseBottomUp(visitor);
    if (thenStr != null) thenStr.traverseBottomUp(visitor);
    if (elseStr != null) elseStr.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("IfThenElse(\n");
      if (e1 != null)
        buffer.append(e1.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append("  "+tab+oprel);
    buffer.append("\n");
      if (e2 != null)
        buffer.append(e2.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (thenStr != null)
        buffer.append(thenStr.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
      if (elseStr != null)
        buffer.append(elseStr.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [IfThenElse]");
    return buffer.toString();
  }
}
