/*
 * Generated by classgen, version 1.5
 * 7/12/17 11:45 AM
 */
package ast;

public class OpArit extends E {

  public E e1;
  public String oparit;
  public E e2;

  public OpArit (E e1, String oparit, E e2) {
    this.e1 = e1;
    if (e1 != null) e1.setParent(this);
    this.oparit = oparit;
    this.e2 = e2;
    if (e2 != null) e2.setParent(this);
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (e1 != null) e1.accept(visitor);
    if (e2 != null) e2.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (e1 != null) e1.traverseTopDown(visitor);
    if (e2 != null) e2.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (e1 != null) e1.traverseBottomUp(visitor);
    if (e2 != null) e2.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("OpArit(\n");
      if (e1 != null)
        buffer.append(e1.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append("  "+tab+oparit);
    buffer.append("\n");
      if (e2 != null)
        buffer.append(e2.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [OpArit]");
    return buffer.toString();
  }
}
