/*
 * Generated by classgen, version 1.5
 * 7/12/17 11:45 AM
 */

package ast;

public interface SyntaxNode extends VisitorNode {
  public SyntaxNode getParent();
  public void setParent(SyntaxNode parent);
}
