/*
 * Generated by classgen, version 1.5
 * 7/12/17 11:45 AM
 */
package ast;

public abstract class VisitorAdaptor implements Visitor {

  public void visit(Args args) { visit(); }
  public void visit(Seq seq) { visit(); }
  public void visit(Block block) { visit(); }
  public void visit(Asm asm) { visit(); }
  public void visit(I i) { visit(); }
  public void visit(Def def) { visit(); }
  public void visit(E e) { visit(); }
  public void visit(NumberExp numberExp) { visit(); }
  public void visit(Ident ident) { visit(); }
  public void visit(IfThenElse ifThenElse) { visit(); }
  public void visit(OpArit opArit) { visit(); }
  public void visit(Decla decla) { visit(); }

  public void visit() { }

}
