/*
 * Generated by classgen, version 1.5
 * 7/12/17 11:45 AM
 */

package ast;

public interface VisitorNode {
  public void accept(Visitor visitor);

  public void childrenAccept(Visitor visitor);
  public void traverseBottomUp(Visitor visitor);
  public void traverseTopDown(Visitor visitor);
}
